### ISSUE TITLE
Can't find glslValidator.exe

### ISSUE THREAD

**Issue by ricanteja** [andystanton/linter-glsl#6]
There is a problem locating the glslValidator. Before the most recent update I had it set up to a specific path but now it can't find it and even if I add it to the System Path it doesn't work. Some change in the most recent update broke this. I'm on Windows 7

Thanks for the neat plugin!

**Comment by andystanton** [comment]
Apologies @ricanteja I didn't test on Windows before the last release.

I've unpublished 1.0.3 until I can test the change on Windows. In the meantime you might need to reinstall linter-glsl as I'm not sure Atom will prompt you to downgrade it to 1.0.2.

**Comment by andystanton** [comment]
apm had problems republishing 1.0.3 so I had to bump up to 1.0.4, but the fix should be in there.

The bug was due to me assuming [fs.assessSync](https://nodejs.org/api/fs.html#fs_fs_accesssync_path_mode) returns a boolean. It doesn't - it throws an exception instead if the required condition isn't met.

Let me know if you have any more issues with this.

**Comment by ricanteja** [comment]
It's fixed! Great work!
